[DQL3-4] Currency email notification
salsadigitalauorg/ckanext-data-qld-theme pull request #14
Opened 2021-08-26 20:56 UTC by tino097

Add js script to handle `next_update_due` and `nature_of_change` fields
Update templates with required changes for showing metadata for authorized users

2021-08-29 23:49 UTC, duttonw commented
some tests are failing on last build, would suggest page failed to load successfully.

```
Failing scenarios:
  test/features/google_analytics.feature:8  When viewing the HTML source code of a dataset, the organisation meta data is visible
  test/features/google_analytics.feature:13  When viewing the HTML source code of a resource, the organisation meta data is visible

4 features passed, 1 failed, 0 skipped
14 scenarios passed, 2 failed, 0 skipped
54 steps passed, 2 failed, 1 skipped, 0 undefined
Took 1m3.573s
```

2021-08-31 16:55 UTC, MarkCalvert requested changes

2021-08-31 16:55 UTC, MarkCalvert commented on ckanext/data_qld_theme/fanstatic/next-update-due.js
> +    UPDATE_FREQUENCY_DAYS = JSON.parse(jQuery('input[name="update_frequency_days"]').val())
Should we set a default value of a empty dict just incase there is no value in the input field etc?

2021-08-31 16:55 UTC, MarkCalvert commented on ckanext/data_qld_theme/fanstatic/resource_file_upload.js
>  jQuery(document).ready(function () {
Add some general comments to help explain the business logic and reasons
Remove extra blank lines etc
Run lint and format the code

2021-08-31 16:55 UTC, MarkCalvert commented on ckanext/data_qld_theme/fanstatic/resource_file_upload.js
> +    if (jQuery('input[name="id"]').val().length > 0) {
Add comment explaining why you are checking for this element and the logic

2021-08-31 16:55 UTC, MarkCalvert commented on ckanext/data_qld_theme/fanstatic/next-update-due.js
> +jQuery(document).ready(function () {
Add some general comments to help explain the business logic and reasons
Remove extra blank lines etc
Run lint and format the code

2021-08-31 16:55 UTC, MarkCalvert commented on ckanext/data_qld_theme/templates/package/snippets/additional_info.html
> +  {%- do exclude_fields.append('next_update_due') -%}
Can any user with editor or admin access to any organisation view this metadata field or is it only users with editor/admin access to this datasets organisation?
If it is the later do a check like `data_qld_show_de_identified_data`

2021-08-31 16:55 UTC, MarkCalvert commented on ckanext/data_qld_theme/templates/scheming/form_snippets/update_due.html
> +
If this is an exact copy of the scheming date form snippet just call the snippet directly.
eg. {%- snippet 'scheming/form_snippets/date.html', field=field, data=data, errors=errors -%}

2021-08-31 23:06 UTC, MarkCalvert approved these changes

2021-08-31 23:07 UTC, merged